;* * * * *  Small-C/Plus z88dk * * * * *
;  Version: 23355-ced5e29acc-20250417
;
;	Reconstructed for z80 Module Assembler
;
;	Module compile time: Sat Apr 19 10:36:40 2025


	C_LINE	0,"main.c"

	MODULE	main_c


	INCLUDE "z80_crt0.hdr"


	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/compiler.h"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/proto.h"
	C_LINE	6,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/compiler.h"
	C_LINE	4,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	5,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	8,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	12,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	15,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	18,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	21,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	24,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	27,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	30,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	33,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	36,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	39,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	42,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	46,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	47,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	48,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	50,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	51,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	52,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	57,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	60,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/sys/types.h"
	C_LINE	11,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	13,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	14,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	15,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	17,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	18,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	19,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	21,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	22,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	23,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	25,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	26,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	27,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	29,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	30,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	31,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	33,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	34,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	35,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	37,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	38,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	40,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	41,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	43,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	44,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	48,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	51,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	53,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	54,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdint.h"
	C_LINE	5,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	49,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	50,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	51,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	52,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	53,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	54,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	55,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	60,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	61,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	62,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	63,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	64,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	65,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	110,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	111,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	112,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	113,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	114,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	115,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	116,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	117,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	118,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	119,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	120,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	121,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	122,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	131,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	132,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	133,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	136,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	137,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	139,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	143,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/malloc.h"
	C_LINE	58,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	14,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	16,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	17,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	19,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	21,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	22,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	25,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	28,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	29,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	31,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	37,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	38,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	39,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	42,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	52,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	60,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	73,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	74,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	76,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	78,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/fcntl.h"
	C_LINE	78,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	85,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	118,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	127,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	131,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	132,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	151,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	154,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	158,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	159,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	160,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	162,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	163,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	167,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	172,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	173,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	175,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	182,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	184,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	186,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	191,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	193,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	197,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	200,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	202,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	204,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	208,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	210,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	213,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	219,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	220,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	224,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	229,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	230,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	233,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	235,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	236,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	237,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	238,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	239,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	240,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	247,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	248,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	249,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	254,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	260,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	261,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	262,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	263,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	264,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	271,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	276,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	281,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	284,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	287,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	290,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	292,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	295,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	297,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	298,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	300,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	302,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	306,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	308,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	312,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	315,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	321,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	323,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	326,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	328,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	330,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdio.h"
	C_LINE	1,"main.c"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	19,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	21,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	24,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	26,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	29,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	31,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	34,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	36,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	39,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	41,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	44,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	46,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	49,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	51,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	54,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	56,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	63,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	65,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	69,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	71,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	75,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	77,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	81,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	83,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	87,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	89,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	98,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	99,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	101,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	127,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	128,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	131,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	132,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	138,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	139,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	140,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	141,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	145,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	148,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	149,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	150,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	151,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	152,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	164,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	165,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	166,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	167,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	171,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	172,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	174,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	175,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	187,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	195,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	203,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	211,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	219,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	221,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	225,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	227,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	231,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	233,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	237,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	239,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	248,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	250,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	253,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	255,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	259,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	261,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	277,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	279,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	282,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	284,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	292,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	296,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	297,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	300,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	301,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	305,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	307,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	310,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	311,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	320,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	322,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	324,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	327,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	329,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	341,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	343,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	347,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	350,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdlib.h"
	C_LINE	2,"main.c"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdbool.h"
	C_LINE	6,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/stdbool.h"
	C_LINE	3,"main.c"
	C_LINE	0,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	4,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	6,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	9,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	11,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	14,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	16,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	19,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	21,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	25,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	27,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	30,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	32,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	35,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	37,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	40,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	42,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	46,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	48,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	51,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	53,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	56,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	58,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	61,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	62,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	63,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	66,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	68,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	71,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	73,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	77,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	79,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	83,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	85,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	88,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	90,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	93,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	95,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	99,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	101,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	104,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	106,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	111,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	113,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	116,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	118,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	121,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	123,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	127,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	129,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	132,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	134,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	137,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	139,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	142,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	144,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	147,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	149,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	152,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	154,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	157,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	159,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	162,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	164,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	167,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	169,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	173,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	175,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	179,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	181,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	185,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	187,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	190,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	192,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	195,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	197,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	201,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	203,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	208,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	210,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	213,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	215,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	218,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	220,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	223,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	225,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	229,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	231,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	234,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	236,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	239,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	241,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	244,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	246,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	249,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	251,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	254,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	256,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	259,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	261,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	264,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	265,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	267,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	271,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	273,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	277,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	278,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	280,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	284,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	286,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	289,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	291,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	294,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	296,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	299,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	301,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	306,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	308,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	311,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	313,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	316,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	318,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	321,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	323,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	327,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	329,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	332,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	333,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	335,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	339,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	341,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	344,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	346,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	351,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	351,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	353,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	355,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	356,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	357,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	359,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	360,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	362,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	363,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	365,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	366,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	368,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	369,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	370,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	372,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	373,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	374,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	375,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	389,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	395,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	401,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	407,"/home/kristofer/LocalProjects/z88dk/lib/config/../..//include/string.h"
	C_LINE	4,"main.c"
	C_LINE	212,"main.c"
	SECTION	code_compiler

; Function main flags 0x00000000 __stdc 
; int main()
	C_LINE	212,"main.c::main::0::1"
._main
	ld	hl,i_1+0
	push	hl
	ld	a,1
	call	printf
	pop	bc
	ld	hl,i_1+7
	push	hl
	ld	a,1
	call	printf
	pop	bc
	ld	hl,0	;const
	ret


	SECTION	bss_compiler
	SECTION	code_compiler
; --- Start of Optimiser additions ---

	SECTION	rodata_compiler
.i_1
	defm	"start"
	defb	10

	defm	""
	defb	0

	defm	"init_lisp"
	defb	10

	defm	""
	defb	0


; --- Start of Static Variables ---

	SECTION	bss_compiler
	SECTION	code_compiler


; --- Start of Scope Defns ---

	GLOBAL	mallinit
	GLOBAL	sbrk
	GLOBAL	calloc
	GLOBAL	free
	GLOBAL	malloc
	GLOBAL	realloc
	GLOBAL	mallinfo
	GLOBAL	malloc_fastcall
	GLOBAL	free_fastcall
	GLOBAL	sbrk_callee
	GLOBAL	calloc_callee
	GLOBAL	realloc_callee
	GLOBAL	mallinfo_callee
	GLOBAL	HeapCreate
	GLOBAL	HeapSbrk
	GLOBAL	HeapSbrk_callee
	GLOBAL	HeapCalloc
	GLOBAL	HeapCalloc_callee
	GLOBAL	HeapFree
	GLOBAL	HeapFree_callee
	GLOBAL	HeapAlloc
	GLOBAL	HeapAlloc_callee
	GLOBAL	HeapRealloc
	GLOBAL	HeapRealloc_callee
	GLOBAL	HeapInfo
	GLOBAL	HeapInfo_callee
	GLOBAL	malloc_far
	GLOBAL	free_far
	GLOBAL	sbrk_far
	GLOBAL	calloc_far
	GLOBAL	realloc_far
	GLOBAL	mallinfo_far
	GLOBAL	freeall_far
	GLOBAL	open
	GLOBAL	creat
	GLOBAL	close
	GLOBAL	read
	GLOBAL	write
	GLOBAL	lseek
	GLOBAL	readbyte
	GLOBAL	writebyte
	GLOBAL	fsync
	GLOBAL	getcwd
	GLOBAL	chdir
	GLOBAL	getwd
	GLOBAL	rmdir
	GLOBAL	__RND_BLOCKSIZE
	GLOBAL	rnd_loadblock
	GLOBAL	rnd_saveblock
	GLOBAL	rnd_erase
	GLOBAL	rnd_erase_fastcall
	GLOBAL	__FOPEN_MAX
	GLOBAL	__sgoioblk
	GLOBAL	__sgoioblk_end
	GLOBAL	fopen_zsock
	GLOBAL	fileno
	GLOBAL	fopen
	GLOBAL	freopen
	GLOBAL	fdopen
	GLOBAL	_freopen1
	GLOBAL	fmemopen
	GLOBAL	funopen
	GLOBAL	fclose
	GLOBAL	fflush
	GLOBAL	closeall
	GLOBAL	fgets
	GLOBAL	fputs
	GLOBAL	fputs_callee
	GLOBAL	fputc
	GLOBAL	fputc_callee
	GLOBAL	fgetc
	GLOBAL	ungetc
	GLOBAL	feof
	GLOBAL	feof_fastcall
	GLOBAL	ferror
	GLOBAL	ferror_fastcall
	GLOBAL	puts
	GLOBAL	ftell
	GLOBAL	fgetpos
	GLOBAL	fseek
	GLOBAL	fread
	GLOBAL	fwrite
	GLOBAL	gets
	GLOBAL	printf
	GLOBAL	fprintf
	GLOBAL	sprintf
	GLOBAL	snprintf
	GLOBAL	vfprintf
	GLOBAL	vsnprintf
	GLOBAL	sprintff
	GLOBAL	snprintff
	GLOBAL	vsnprintff
	GLOBAL	printn
	GLOBAL	scanf
	GLOBAL	fscanf
	GLOBAL	sscanf
	GLOBAL	vfscanf
	GLOBAL	vsscanf
	GLOBAL	getarg
	GLOBAL	fchkstd
	GLOBAL	fgetc_cons
	GLOBAL	fgetc_cons_inkey
	GLOBAL	fputc_cons
	GLOBAL	fgets_cons
	GLOBAL	puts_cons
	GLOBAL	fabandon
	GLOBAL	fdtell
	GLOBAL	fdgetpos
	GLOBAL	rename
	GLOBAL	remove
	GLOBAL	getk
	GLOBAL	getk_inkey
	GLOBAL	printk
	GLOBAL	perror
	GLOBAL	set_fputc_cons
	GLOBAL	fputc_cons_native
	GLOBAL	fputc_cons_generic
	GLOBAL	fputc_cons_ansi
	GLOBAL	atoi
	GLOBAL	atoi_fastcall
	GLOBAL	atol
	GLOBAL	atol_fastcall
	GLOBAL	itoa
	GLOBAL	itoa_callee
	GLOBAL	ltoa
	GLOBAL	ltoa_callee
	GLOBAL	strtol
	GLOBAL	strtol_callee
	GLOBAL	strtoul
	GLOBAL	strtoul_callee
	GLOBAL	ultoa
	GLOBAL	ultoa_callee
	GLOBAL	utoa
	GLOBAL	utoa_callee
	GLOBAL	_atoll
	GLOBAL	_atoll_callee
	GLOBAL	_lltoa
	GLOBAL	_lltoa_callee
	GLOBAL	_strtoll
	GLOBAL	_strtoll_callee
	GLOBAL	_strtoull
	GLOBAL	_strtoull_callee
	GLOBAL	_ulltoa
	GLOBAL	_ulltoa_callee
	GLOBAL	rand
	GLOBAL	srand
	GLOBAL	srand_fastcall
	GLOBAL	exit
	GLOBAL	atexit
	GLOBAL	exit_fastcall
	GLOBAL	atexit_fastcall
	GLOBAL	getenv
	GLOBAL	getenv_r
	GLOBAL	setenv
	GLOBAL	unsetenv
	GLOBAL	getopt
	GLOBAL	_optarg
	GLOBAL	_opterr
	GLOBAL	_optind
	GLOBAL	_optopt
	GLOBAL	_optreset
	GLOBAL	l_bsearch
	GLOBAL	l_bsearch_callee
	GLOBAL	l_qsort
	GLOBAL	l_qsort_callee
	GLOBAL	qsort_sccz80
	GLOBAL	qsort_sccz80_callee
	GLOBAL	qsort_sdcc
	GLOBAL	qsort_sdcc_callee
	GLOBAL	_div_
	GLOBAL	_div__callee
	GLOBAL	_divu_
	GLOBAL	_divu__callee
	GLOBAL	_ldiv_
	GLOBAL	_ldiv__callee
	GLOBAL	_ldivu_
	GLOBAL	_ldivu__callee
	GLOBAL	abs
	GLOBAL	abs_fastcall
	GLOBAL	labs
	GLOBAL	labs_fastcall
	GLOBAL	isqrt
	GLOBAL	isqrt_fastcall
	GLOBAL	inp
	GLOBAL	inp_fastcall
	GLOBAL	outp
	GLOBAL	outp_callee
	GLOBAL	swapendian
	GLOBAL	bpoke
	GLOBAL	wpoke
	GLOBAL	bpeek
	GLOBAL	wpeek
	GLOBAL	bpeek_fastcall
	GLOBAL	wpeek_fastcall
	GLOBAL	bpoke_callee
	GLOBAL	wpoke_callee
	GLOBAL	t_delay
	GLOBAL	sleep
	GLOBAL	sleep_fastcall
	GLOBAL	msleep
	GLOBAL	msleep_fastcall
	GLOBAL	extract_bits
	GLOBAL	extract_bits_callee
	GLOBAL	wcmatch
	GLOBAL	unbcd
	GLOBAL	bcmp
	GLOBAL	bcmp_callee
	GLOBAL	bcopy
	GLOBAL	bcopy_callee
	GLOBAL	bzero
	GLOBAL	bzero_callee
	GLOBAL	index
	GLOBAL	index_callee
	GLOBAL	rindex
	GLOBAL	rindex_callee
	GLOBAL	strset
	GLOBAL	strset_callee
	GLOBAL	strnset
	GLOBAL	strnset_callee
	GLOBAL	rawmemchr
	GLOBAL	rawmemchr_callee
	GLOBAL	_memlwr_
	GLOBAL	_memlwr__callee
	GLOBAL	_memstrcpy_
	GLOBAL	_memstrcpy__callee
	GLOBAL	_memupr_
	GLOBAL	_memupr__callee
	GLOBAL	_strrstrip_
	GLOBAL	ffs
	GLOBAL	ffsl
	GLOBAL	memccpy
	GLOBAL	memccpy_callee
	GLOBAL	memchr
	GLOBAL	memchr_callee
	GLOBAL	memcmp
	GLOBAL	memcmp_callee
	GLOBAL	memcpy
	GLOBAL	memcpy_callee
	GLOBAL	memmem
	GLOBAL	memmem_callee
	GLOBAL	memmove
	GLOBAL	memmove_callee
	GLOBAL	memrchr
	GLOBAL	memrchr_callee
	GLOBAL	memset
	GLOBAL	memset_callee
	GLOBAL	memset_wr
	GLOBAL	memset_wr_callee
	GLOBAL	memswap
	GLOBAL	memswap_callee
	GLOBAL	stpcpy
	GLOBAL	stpcpy_callee
	GLOBAL	stpncpy
	GLOBAL	stpncpy_callee
	GLOBAL	strcasecmp
	GLOBAL	strcasecmp_callee
	GLOBAL	strcat
	GLOBAL	strcat_callee
	GLOBAL	strchr
	GLOBAL	strchr_callee
	GLOBAL	strchrnul
	GLOBAL	strchrnul_callee
	GLOBAL	strcmp
	GLOBAL	strcmp_callee
	GLOBAL	strcoll
	GLOBAL	strcoll_callee
	GLOBAL	strcpy
	GLOBAL	strcpy_callee
	GLOBAL	strcspn
	GLOBAL	strcspn_callee
	GLOBAL	strdup
	GLOBAL	strdup_fastcall
	GLOBAL	strerror
	GLOBAL	strerror_fastcall
	GLOBAL	stricmp
	GLOBAL	stricmp_callee
	GLOBAL	strlcat
	GLOBAL	strlcat_callee
	GLOBAL	strlcpy
	GLOBAL	strlcpy_callee
	GLOBAL	strlen
	GLOBAL	strlen_fastcall
	GLOBAL	strlwr
	GLOBAL	strlwr_fastcall
	GLOBAL	strncasecmp
	GLOBAL	strncasecmp_callee
	GLOBAL	strncat
	GLOBAL	strncat_callee
	GLOBAL	strnchar
	GLOBAL	strnchr_callee
	GLOBAL	strncmp
	GLOBAL	strncmp_callee
	GLOBAL	strncpy
	GLOBAL	strncpy_callee
	GLOBAL	strndup
	GLOBAL	strndup_callee
	GLOBAL	strnicmp
	GLOBAL	strnicmp_callee
	GLOBAL	strnlen
	GLOBAL	strnlen_callee
	GLOBAL	strpkbrk
	GLOBAL	strpbrk_callee
	GLOBAL	strrchr
	GLOBAL	strrchr_callee
	GLOBAL	strrcspn
	GLOBAL	strrcspn_callee
	GLOBAL	strrev
	GLOBAL	strrev_fastcall
	GLOBAL	strrspn
	GLOBAL	strrspn_callee
	GLOBAL	strrstrip
	GLOBAL	strrstrip_fastcall
	GLOBAL	strsep
	GLOBAL	strsep_callee
	GLOBAL	strspn
	GLOBAL	strspn_callee
	GLOBAL	strstr
	GLOBAL	strstr_callee
	GLOBAL	strstrip
	GLOBAL	strstrip_fastcall
	GLOBAL	strtok
	GLOBAL	strtok_callee
	GLOBAL	strtok_r
	GLOBAL	strtok_r_callee
	GLOBAL	strupr
	GLOBAL	strupr_fastcall
	GLOBAL	strxfrm
	GLOBAL	strxfrm_callee
	GLOBAL	strrstr
	GLOBAL	strrstr_callee
	GLOBAL	memopi
	GLOBAL	memopi_callee
	GLOBAL	memopd
	GLOBAL	memopd_callee
	GLOBAL	strdupf
	GLOBAL	strlenf
	GLOBAL	strcasecmpf
	GLOBAL	strcmpf
	GLOBAL	strncmpf
	GLOBAL	strcpyf
	GLOBAL	strncpyf
	GLOBAL	strcatf
	GLOBAL	strncatf
	GLOBAL	strlwrf
	GLOBAL	struprf
	GLOBAL	strchrf
	GLOBAL	strnchrf
	GLOBAL	strrchrf
	GLOBAL	memcpyf
	GLOBAL	memsetf
	GLOBAL	memchrf
	GLOBAL	memcmpf
	GLOBAL	__builtin_memset
	GLOBAL	__builtin_memcpy
	GLOBAL	__builtin_strcpy
	GLOBAL	__builtin_strchr
	GLOBAL	_main


; --- End of Scope Defns ---


; --- End of Compilation ---
